### ISSUE TITLE
Love App Store (parent)

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#10]
Love App Store, codename "Vapor". Well something like that.
This could be a replacement to fun no-game screen, it'd be a huge breakthrough. If no network available, throw the normal no game screen to the user. This would rely on networking fully and interacts with #7.

Sub issues:
Searching: #11 
Ranking: #12 
Sections: #13
Tagging: #14

**Comment by karai17** [comment]
This... is a really good idea. Integrating Vapor into love itself would be super useful for both developers and non-developers alike. Maybe even integrating an upload/submission form in vapor/love so that when a person is confident that their game is ready for release, it can be submitted right from the no-game screen for approval.

**Comment by qaisjp** [comment]
security issues

**Comment by josefnpat** [comment]
@karai17 This might be something good to open a ticket for.

At some point we want to bundle OpenSSL and LuaSec to vapor.

**Comment by josefnpat** [comment]
Closing as the issues have already been created.
