### ISSUE TITLE
OS X Lockup

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#105]
Re: Vapor - LÖVE Distribution Client
by FireZenk on Tue Sep 17, 2013 5:11 am

In Mountain Lion Mac gets stuck on the loading screen :(

**Comment by josefnpat** [comment]
What version of vapor were you using?
Can you determine exactly where it is locking up?
Did you have internet at the time?

**Comment by qaisjp** [comment]
I can guess this is the same issue I have and what I've reported. I'll send you some information, I'd test the latest revision but it means I have to use run.sh and I've already reported the issue with the release.

**Comment by josefnpat** [comment]
@qaisjp Can you link to what issue you think this is related to? He says it "gets stuck", which doesn't sound like #94

**Comment by qaisjp** [comment]
It is the exact same thing. When running the release it just shows a blue window, a 5(?) pixel tall window which is blue and a loading title. I had to run it through terminal to see if it was loading or if it was an error. So he thought it got stuck because it was saying "Loading..." in the title the entire time.

**Comment by josefnpat** [comment]
Ah! Thanks @qaisjp . I'm closing and marking this a duplicate.

**Comment by josefnpat** [comment]
A duplicate of #94 I might add ...
