### ISSUE TITLE
Choose a license for the project

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#113]

**Comment by ncarlson** [comment]
Would you guys mind attaching a license to this code? Thank you.

**Comment by josefnpat** [comment]
@ncarlson that's what this ticket is about :)

**Comment by leafo** [comment]
My contributions to this project are public domain so feel free to do whatever you want with the code.

**Comment by ncarlson** [comment]
Thank you.

**Comment by josefnpat** [comment]
@leafo this was the question I was going to ask you in private! Thanks!

**Comment by Yonaba** [comment]
[NothingSerious]You didn't use [lice-lua](http://github.com/licenses/lice-lua). I hate you. :)[/NothingSerious]

I might be quibbling, but why using markdown for the license file ? I was thinking that people would commonly leave this file with no extension, so that Unixes will assume those are plain text ?

**Comment by josefnpat** [comment]
The readme was in markdown, I guess I really didn't think of it. Thanks.

**Comment by Yonaba** [comment]
Sweet!
