### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#13]
Vapor could contain multiple categories: Featured, New, Categories, Pinned

Featured would just be the charts of the top rated games and it'd depend on whether people like the reviews made for it. As seen in #12 

The "New" would feature two tabs, Development and Completed. This will help raise awareness for new games. 

Categories would just show things like "Puzzle, Arcade, Utilities" etc. Ordered by popularity in ascending order.

Pinned, (renaming from starred to pinned), contains all your favourite "apps" (using apps here because love2d can also serve utilities) which you pinned.

This would be tightly connected to whatever system Vapor uses for catalogue storage (games.json).

**Comment by josefnpat** [comment]
This issue is very close to #14, but with one very important distinction;

Categories are relations that come from the `games.json` and are non-editable by the client, and tagging is available to the client.

https://github.com/hawkthorne/hawkthorne-journey/issues/1687#issuecomment-22484572

The `games.json` should be created in a way to easily add new categories.

Instead of having an index key scheme (e.g. `"new":true,"featured":true,"game":false`) we ought to use a category index (e.g. `"category":["new","featured"]`

**Comment by qaisjp** [comment]
wait a minute, tagging is by the game authors. to tag special things to
help search find their program. for example Giga Pudding would have
"cartoon" etc
This would be hidden to the user and only assists in making the search more
optimised. Search goes through words in the title and words in the tags. So
you won't need to put "giga" "pudding" in tags.

**Comment by qaisjp** [comment]
tags can be named anything, categories are limited to predefined ones
inside vapor. authors set the tags/category of their game, but they can
only choose from a list of categories. they can put any tag they want.

**Comment by josefnpat** [comment]
@qaisjp 
I agree, but why should we not have an abstract system to make it easy to add new categories?

**Comment by qaisjp** [comment]
make it possible to add cats via the website developer dashboard thingy, but the categories have to be accepted by the Vapor administrators like most other updates.
