### ISSUE TITLE
Submitting Love for Zombies

### ISSUE THREAD

**Issue by Yonaba** [josefnpat/vapor#142]
Hi,

Submitting [Love For Zombies](https://github.com/Ellohir-noldo/Love-for-zombies), a zombie killing game.
A nice playable prototype, polished. Though difficult (or maybe I am too slow).
Author is @Ellohir-noldo

Side note, resolution is 512x512. Dunno if this is an issue, actually...

Regards,
Roland.

**Comment by Ellohir-noldo** [comment]
Hi,

I'd love it to be included in Vapor, it's such a great idea. If @josefnpat thinks a different resolution would be fit it better, we can change it.

Regards,
Ellohir

**Comment by josefnpat** [comment]
@Yonaba The game does scale to 1024x1024 under the settings menu.

@Ellohir-noldo Thanks for responding! The strict rule is that the game can't be started in fullscreen, so your game as is, is just fine. It would be nice if the game scaled to somewhere between 512 and 1024, but that's your call in the end.

If you are comfortable with git and json, you can provide a pull request to vapor.

If you are not, please provide us with as much of the required information as possible so that we can set it up for you!

Here is the information we need: https://github.com/josefnpat/vapor#how-can-i-add-my-game

If you need http hosting for your .love and image, I am more than happy to provide this for you.
