### ISSUE TITLE
Distribute vapor in a Flatpak

### ISSUE THREAD

**Issue by LeandroStanger** [josefnpat/vapor#204]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by josefnpat** [comment]
Howdy!

Not sure if you checked the dates on the release, but this hasn't had a release since 2013. I'm not even sure if the drupal backend is still functional to be honest. 

I think it's reasonable to say that this project is no longer being maintained.

If you, regardless, have a desire to deploy this project as a flatpack, feel free to - this is under the zlib/libpng License.
