### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by SiENcE** [josefnpat/vapor#37]
Games loading works on windows 7 (64bit) but not playing. Executable not found.

I used love.exe vapor_8badcc1.love to start.

It might be a good idea, to download the needed love runtime from the love2d.org website and put it into the %appdata%/LOVE folder where the downloaded files are. Than you can start the correct Love version from there.

For downloading the right love runtime, we might need an authentification. The best way would be an https connection (with check for root & user certificate). Otherwise it's too risky (dns aso.).

**Comment by josefnpat** [comment]
`Games loading works on windows 7 (64bit) but not playing. Executable not found. I used love.exe vapor_8badcc1.love to start.`

`8badcc1` was after the "windows fix" so this is a valid ticket. Can you tell me how you installed love?

`It might be a good idea, to download the needed love runtime from the love2d.org website and put it into the %appdata%/LOVE folder where the downloaded files are. Than you can start the correct Love version from there.`

We actually use the `love.exe` that runs vapor, by pulling the binary location from the `args`

https://github.com/josefnpat/vapor/blob/8badcc1639ce9091a652fd2be53ba89692cd6b27/src/main.lua#L48

`For downloading the right love runtime, we might need an authentification. The best way would be an https connection (with check for root & user certificate). Otherwise it's too risky (dns aso.).`

I would LOVE to use https (FOR EVERYTHING) but unfortunatly, without luasec included in love, we would have to distribute a binary module (which complicates distribution tenfold). At some point we're going to have to get https (or some alternative) if we ever want to authenticate accounts, but we're not that far yet. #2 has some talk about this.

At this line:

https://github.com/josefnpat/vapor/blob/8badcc1639ce9091a652fd2be53ba89692cd6b27/src/main.lua#L31

Could you please add `print(exe)` and paste the output from the console here?

**Comment by josefnpat** [comment]
Added #39 as from this ticket.

**Comment by josefnpat** [comment]
```
12:08 <Boolsheet> josefnpat: I think you're using start wrong. 
12:08 <Boolsheet> try 'start "" "love.exe" "game.love"'
...
12:09 <Boolsheet> That works here.
```

**Comment by josefnpat** [comment]
Please try switching https://github.com/josefnpat/vapor/blob/master/src/main.lua#L35 from

`exe = "start \""..binary.."\" \"".."%appdata%/LOVE/vapor-data".."/"..fname(gameobj,gameobj.stable).."\""`

to

`exe = "start \"\" \""..binary.."\" \"".."%appdata%/LOVE/vapor-data".."/"..fname(gameobj,gameobj.stable).."\""`

**Comment by josefnpat** [comment]
Waiting on confirmation from @SiENcE

**Comment by SiENcE** [comment]
Confirmed and working!

**Comment by josefnpat** [comment]
<3

**Comment by qaisjp** [comment]
:+1:
