### ISSUE TITLE
Hashing performance issue on Non-JIT compiled versions of love

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#41]
@boolsheet reports `2.1 seconds for 1 MiB.`

Really need to thread this in the background while this happens.

**Comment by qaisjp** [comment]
Should we create a Coroutine utility? A function that accepts infinite arguments. First arg must be a function to execute non-blocking and the rest are args for that function passed in first argument ( using ... )

**Comment by josefnpat** [comment]
Can't we just fire off a new thread?

https://www.love2d.org/wiki/love.thread.newThread

**Comment by josefnpat** [comment]
What if we offered a settings window that allowed the user to enable and disable sha1 checking?

Like everyone mentions in IRC, we really need to thread this in the background.

**Comment by Germanunkol** [comment]
I think the best solution is using a thread. They're straight forward, they can access the file and they work very well in love.
Since the file is stored on the PC, the thread only needs the path to the file. Then it can work on it and later report the sha sum back to the main thread, and end.

And I really dislike the idea of being able to switch of sha1 checking. I think it should be mandatory - it really makes everything nice and safe. When it's threadded, I don't see a reason why it shouldn't stay - 2.1 seconds is no problem if your program doesn't freeze up.

**Comment by qaisjp** [comment]
:+1: @Germanunkol

**Comment by Germanunkol** [comment]
Here's someone who enabled threading for hashing. This should do fine for vapor?
https://love2d.org/forums/viewtopic.php?f=4&t=57472
It's pretty straight forward...

(Sorry about posting in the wrong thread before. I was looking for this one and didn't find it O.o - I was confused by the "Non-JIT" part in the title.)
