### ISSUE TITLE
Get Wake Up Call into vapor

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#60]
https://love2d.org/forums/viewtopic.php?f=5&t=9339

**Comment by josefnpat** [comment]
I don't see a license associated with this project, I so we can't push this into vapor without contacting the author.

**Comment by mz1-One** [comment]
License is: Distribute at will! Here's the JSON. Thanks!

{
      "id":"wake_up_call",
      "stable":"1386371787",
      "sizes":{
        "22584049":
      },
      "engine":"love-0.8.0",
      "hashes":{
        "1386371787":"582A9A93ACC91A1EB1D2B1592555B95379EB8E70"
      },
      "image":"www.mz1net.com/wakeupcall/rep/wake_up_call_-_vapor_thumbnail.jpg",
      "author":"mz1",
      "website":"http://www.mz1net.com",
      "sources":{
        "1386371787":"https://dl.dropbox.com/u/59488139/WakeUpCall/wakeUpCall_v1.1.love"
      },
      "name":"Wake up call",
      "description":"An experimental interactive piece that takes place inside a comatose man’s mind. Will you be able to wake up back into consciousness?"
    },

**Comment by josefnpat** [comment]
@mz1-One This is great!

Everything here looks fine, **except the dropbox link**. If you do not want to host it on an http protocol (like your site, http://mz1net.com) **I would be happy to mirror it onto my server**.

_As an aside, and this is not important unless you are submitting this via a pull request, the sha1sum needs to be lowercase. I can easily re-calculate the value. If you would would like to submit a pull request, this is important :)_

**Comment by josefnpat** [comment]
@mz1-One Also, are you interested in getting Netherworld [Demo] in vapor? I don't know if that is still an active project.

**Comment by mz1-One** [comment]
Sure, let's use this one instead, then>
http://www.mz1net.com/wakeupcall/rep/wakeUpCall_v1.1.love

The lowercase hash is "582a9a93acc91a1eb1d2b1592555b95379eb8e70" – There's no need to do a pull request, please add this to where it needs to be, so that it's all done :-) 

Netherworld is not in active development – I had to leave it when the IndieGoGo didn't work out, because I was sure I wouldn't have time to do it well. Still, the demo is consistent and well-polished and can even actually be completed. I would love to have it vaporised! Where do kinda "complete demos" stand in Vapor terms?

**Comment by josefnpat** [comment]
@mz1-One So long as it hits [these requirements](https://github.com/josefnpat/vapor#game-criteria), it's no problem :)

Demos are fine, so long as they're playable.
