### ISSUE TITLE
Consider mirroring all data onto bitbucket

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#68]
I know that we're using sha1 hashes, so the authenticity of the file isn't in question, but there is a question of whether the data will be available.

bitbucket's data policy describes "fair use"

https://confluence.atlassian.com/pages/viewpage.action?pageId=273877699

I could also consider hosting all the files myself.

**Comment by qaisjp** [comment]
easy if you just use the "git mirror" feature or something like that.
but i really dont see the point, github all the way

**Comment by Germanunkol** [comment]
Are you talking about Vapor's data or the games' data?

I think a secondary mirror that's automatically created for each new entry would be good.
Idea: when the games.json gets a new entry, some main server script automatically pulls a copy of it and the vapor client then gets an alternative download link from this - in case the original server hosting the game ever goes offline.
Space should not be the issue here at this point - even if there'll be a few hundred games, this can still go into a normal webspace... maybe ask around on the forum, I'm sure there's someone around with 100 Gb to spare?

**Comment by josefnpat** [comment]
I'm talking about all of vapor's games' data.

But I do like the open source "Become a mirror" thing where server owners would be able to host the .love files, and users could select mirrors.

Might be nice to distribute an `update.php` that would sync the mirror with the `games.json` from this github repo.

**Comment by josefnpat** [comment]
@Spec0pAssassin hit me up on IRC, and he says he would be willing to offer a mirror!

Doing something like this would mean a full API change (0.2 anyone :) ), as the `games.json` file would have to shift from full URL links to base urls (`trAInspotted4.love`) and a official mirror index.

This also will cause issues with #7 as we were considering integrating more deeply with itch.io

It might be a great way to "distribute the load" though.

**Comment by josefnpat** [comment]
Everything has been mirrored onto a drupal instance.
